// Generated by https://quicktype.io

import { TipoEstatus } from "./tipo.estatus.model";

export interface Estatus {
    id:             number;
    desc:           string;
    tipo:           TipoEstatus;
    siguiente:      number;
    siguienteError: number;
}
